type: genetic
optimizer: genetic
criterion: corrsig_fit
epochs: 100 # Number of generations
partition: # Genome partition
  - 4
  - 22
stop_threshold: 1.0
track_running_stats: False
# This is now automatically obtained from the model from the info dictionary, but it can also be defined as follows:
generange:
  [
    [-0.55, 0.325],
    [-0.95, 0.55],
    [-1.0, 0.6],
    [-1.0, 0.6],
    [-1.0, 0.6],
    [-0.95, 0.55],
    [-0.55, 0.325],
  ]
