processor_type: cdaq_to_cdaq
input_indices: # It specifies the indices of the activation data array that will be considered as inputs
  - 3
  - 6
waveform:
  plateau_length: 30
  slope_length: 30
info:
  sampling_frequency: 10000
  electrode_info:
    electrode_no: 8
    activation_electrodes:
      electrode_no: 7
      voltage_ranges:
        [
          [-0.7, 1.2],
          [-0.3, 0.4],
          [-0.7, 1.2],
          [-0.8, 1.1],
          [-0.6, 1.1],
          [-0.3, 0.5],
          [-0.7, 1.1],
        ]
    output_electrodes:
      electrode_no: 1
      amplification: [41]
      clipping_value: [-160, 160]
driver:
  real_time_rack: False # Driver can be local or remote. Remote for the RT NI Rack (Pinky), and local for the regular one (Brains).
  sampling_frequency: 10000 # Sampling frequency at which NI modules will write and read
  amplification:
    [41] # Amplification correction applied in software, to revert the amplification created in hardware in order to read the output current. It is different for each setup.
    # BRAINS: 28.5
    # DARWIN: 100 # Can also vary dependent on where the knob is.
  instruments_setup:
    sampling_frequency: 10000
    multiple_devices: False # Whether if the driver will be reading simultaneously a single or multiple devices.
    trigger_source: cDAQ1/segment1
    activation_instrument: cDAQ1Mod3
    activation_channels: [6, 0, 1, 5, 2, 4, 3]
    activation_voltage_ranges:
      [
        [-0.7, 1.2],
        [-0.3, 0.4],
        [-0.7, 1.2],
        [-0.8, 1.1],
        [-0.6, 1.1],
        [-0.3, 0.5],
        [-0.7, 1.1],
      ]
    readout_instrument: cDAQ1Mod4
    readout_channels: [0] #ai4
    activation_channel_mask: [1, 1, 1, 1, 1, 1, 1]
