processor_type: cdaq_to_cdaq
input_indices: # It specifies the indices of the activation data array that will be considered as inputs
  - 4 #AO2
  - 0 #AO6
waveform:
  plateau_length: 40
  slope_length: 40
driver:
  instrument_type: cdaq_to_cdaq
  real_time_rack: False # Driver can be local or remote. Remote for the RT NI Rack (Pinky), and local for the regular one (Brains).
  amplification: 41
  inverted_output: True # Whether the amplification of the OP-Amp in the PCB is an inverting one.
  instruments_setup: 
    multiple_devices: False
    trigger_source: cDAQ1/segment1
    average_io_point_difference: True # If there is a difference in the number of readout points w.r.t. the written points, it will return the average. 
    activation_sampling_frequency: 10000
    readout_sampling_frequency: 10000
    average_io_point_difference: False
    activation_instrument: cDAQ1Mod3
    activation_channels: [6,0,1,5,2,4,3] #ao
    activation_voltage_ranges: [[-0.9,0.5],[-0.3,0.5],[-0.9,0.9],[-1,1],[-0.9,0.6],[-0.6,0.3],[-1,1]] #[[-0.08,0.08],[-0.08,0.08],[-0.08,0.08],[-0.08,0.08],[-0.08,0.08],[-0.08,0.08],[-0.08,0.08]]  
    activation_channel_mask: [1,1,1,1,1,1,1]
    readout_instrument: cDAQ1Mod4
    readout_channels: [0]
