data:
  input_indices: # It specifies the indices of the activation data array that will be considered as inputs
    - 1
    - 2
  waveform: 
    plateau_length: 30 
    slope_length: 30
driver:
  instrument_type: cdaq_to_cdaq # Possible values are: simulation, simulation_debug, cdaq_to_cdaq, and cdaq_to_nidaq 
  real_time_rack: False # Driver can be local or remote. Remote for the RT NI Rack (Pinky), and local for the regular one (Brains).
  sampling_frequency: 1000
  amplification: 28.5
  instruments_setup:
      multiple_devices: False
      trigger_source: cDAQ1/segment1       
      activation_instrument: cDAQ1Mod3
      activation_channels: [0,2,5,3,4,6,1]
      activation_voltage_ranges:  [[-0.7,0.3],[-1.2,0.7],[-1.2,0.7],[-1.2,0.7],[-1.2,0.7],[-1.2,0.7],[-0.7,0.3]]
      readout_instrument: cDAQ1Mod4
      readout_channels: [4] #ai4
      activation_channel_mask: [1,1,1,1,1,1,1]