multiple_devices: False
trigger_source: cDAQ1/segment1
average_io_point_difference: True # If there is a difference in the number of readout points w.r.t. the written points, it will return the average. 
activation_sampling_frequency: 10000
readout_sampling_frequency: 10000
average_io_point_difference: False
activation_instrument: cDAQ1Mod3
activation_channels: [6,0,1,5,2,4,3] #ao
activation_voltage_ranges: [[-0.9,0.5],[-0.3,0.5],[-0.9,0.9],[-1,1],[-0.9,0.6],[-0.6,0.3],[-1,1]] #[[-0.08,0.08],[-0.08,0.08],[-0.08,0.08],[-0.08,0.08],[-0.08,0.08],[-0.08,0.08],[-0.08,0.08]]  
activation_channel_mask: [1,1,1,1,1,1,1]
readout_instrument: cDAQ1Mod4
readout_channels: [0]
