from_dimension: 4
to_dimension: 7
threshold_parameter: 0.5
max_attempts: 5
results_base_dir: "tmp/TEST/output/boolean"
data:
  batch_size: 512
  worker_no: 0
  pin_memory: True
algorithm: !include defaults/algorithms/gd/boolean.yaml
accuracy: !include defaults/perceptron/accuracy.yaml #Configurations for the perceptron
processor:
  processor_type: "simulation" # Possible values are: simulation, simulation_debug, cdaq_to_cdaq, and cdaq_to_nidaq
  model_dir: "training_data.pt"
  input_indices: # It specifies the indices of the activation data array that will be considered as inputs
    - 1
    - 2
  electrode_effects:
    amplification: [28.5] # It always has to be a list
    clipping_value: None
    #noise:
    #  type: gaussian
    #  variance: 0.65
  waveform:
    plateau_length: 3
    slope_length: 0
