from_dimension: 4
to_dimension: 7
threshold_parameter: 0.5
max_attempts: 5
results_base_dir: "tmp/TEST/output/boolean"
data:
  batch_size: 512
  worker_no: 0
  pin_memory: True
algorithm: !include defaults/algorithms/ga/boolean.yaml
accuracy: !include defaults/perceptron/accuracy.yaml #Configurations for the perceptron
processor: !include defaults/processors/simulation_boolean.yaml
